// projects-site/public/blog-site/React/src/Comment.js
import React from 'react';

function Comment ({comment: {name, email, body}}) {

        return (
            <main id="commentDiv" >
                <section id="commentSection"><span id="name">Name:  </span>{name}<br/><span id="email">
                    e-mail: </span>{email}<br/><span id="comment">Comment: </span>{body}</section><hr/>
            </main>
        );
}

export default Comment;

// projects-site/public/blog-site/Angular/src/app/blogs/user/get-posts/post/get-comments/comment/comment.component.ts
import { Component, Input, OnInit } from '@angular/core';
import {Comment} from 'src/app/shared/Comment';


@Component({
  selector: 'app-comment',
  templateUrl: './comment.component.html',
  styleUrls: ['./comment.component.css']
})
export class CommentComponent implements OnInit {

  @Input()
  comment!: Comment;

  constructor() { }

  ngOnInit(): void {
  }

}

<main id="commentDiv" >
  <section id="commentSection"><span id="name">Name:  </span>{{comment.name}}<br/><span id="email">
      e-mail: </span>{{comment.email}}<br/><span id="comment">Comment: </span>{{comment.body}}</section><hr/>
</main>
